Refactor JWT Websocket Authorization
amitripshtos/starlette-jwt pull request #7
Opened 2019-11-21 08:03 UTC by ralfzen

## Purpose
Most web browsers are not supporting headers in their WebSocket implementation for security reasons.
The authorization via `query parameters` is the recommended alternative.

## Approach
Add a `JWTWebSocketAuthenticationBackend` middleware for this use case.

2019-11-24 16:38 UTC, amitripshtos requested changes
Hey,
Thanks for updating the pull request.
Can you please fix the coverage issues? We want to keep the coverage high.

Also, I have some small comment about a line of code - please fix that and I will approve it.
Thanks!

2019-11-24 16:38 UTC, amitripshtos commented on starlette_jwt/middleware.py
> +        if "jwt" not in request.query_params:
Please use the self.query_param_name

2020-01-07 14:30 UTC, ralfzen commented on starlette_jwt/middleware.py
> +        if "jwt" not in request.query_params:
Good catch! Resolved.

2020-01-07 14:58 UTC, ralfzen commented
@amitripshtos Also the coverage is fixed and now at 100%.

2020-01-08 11:46 UTC, amitripshtos approved these changes

2020-01-08 11:46 UTC, merged